# SITE CONFIGURATION
title: Vinicius Assef
author: viniciusban
url: "https://viniciusban.com"
baseurl: ""
img_dir: "/assets/img"  # by viniciusban

description: >
  These are my opinions acquired through my experience, but they can change.


# SEO PLUGIN
social:
  name: viniciusban
  links:
    - https://twitter.com/viniciusban
    - https://www.linkedin.com/in/viniciusban
    - https://github.com/viniciusban

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Categories', link: '/categories'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  i have much more questions than answers

hero_img: posts/iron-horse.jpg

email: viniciusban@gmail.com # email for form submission

twitter_username: viniciusban
github_username:  viniciusban
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: viniciusban

google_tag_manager: UA-143818570-1

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
#permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
